name: ogrenci_takip_sistemi
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  provider: ^6.1.4
  file_picker: ^8.3.3
  excel: ^2.0.4
  sqflite: ^2.4.1
  flutter_pdfview: ^1.4.0
  path: ^1.9.0
  tuple: ^2.0.0

  shared_preferences: ^2.2.2

  multi_select_flutter: ^4.1.3
  intl: 0.19.0
  http: ^1.3.0
  http_parser: ^4.1.2
  fl_chart: ^0.70.2
  pdf: 3.10.1
  syncfusion_flutter_charts: ^28.2.4+1
  printing: ^5.14.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  image_picker: ^1.1.2
  flutter_localizations:
    sdk: flutter
  dropdown_textfield: ^1.2.0
  path_provider: ^2.1.5
  open_file: ^3.5.10

  calendar_view: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15

flutter:
  uses-material-design: true

  assets:
    - assets/DejaVuSans.ttf
    - assets/dejavu-sans-bold.ttf
    - assets/default_avatar.png
    - assets/icons/pdf.png
    - assets/icons/pdf(1).png
    - assets\icons\atmospheric-conditions.png
    - assets\icons\teacher.png
    - assets\icons\student.png
    - assets\icons\assigned.png
    - assets\icons\assign.png
    - assets\icons\assignment.png
    - assets\icons\data.png
    - assets\icons\user-account.png
    - assets\icons\about.png
    - assets\icons\sheet.png
